name: Run Renovate

on:
  workflow_dispatch:  # 👈 allows manual trigger from GitHub UI

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v42.0.5
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}

